---
# Configuration sample file for Jingo (YAML)
application:
  title: DQJK
  repository: 'blog'
  docSubdir: ''
  remote: 'origin'
  pushInterval: 30
  secret: change me
  git: git
  skipGitCheck: false
  loggingMode: 1
  pedanticMarkdown: true
  gfmBreaks: true
  staticWhitelist: "/\\.png$/i, /\\.jpg$/i, /\\.gif$/i"
authentication:
  google:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
  github:
    enabled: true
    clientId: dqjkwujin@live.cn
    clientSecret: replace me with the real value
  local:
    enabled: false
    accounts:
      - username: 'dqjk'
        passwordHash: '0edd12ed512c94b047218e82b15205dec423b1f2'
        email: 'dqjkwujin@gmail.com'
features:
  markitup: false
  codemirror: true
server:
  hostname: localhost
  port: 6067
  localOnly: false
  baseUrl: ''
authorization:
  anonRead: true
  validMatches: .+
pages:
  index: Home
  title:
    fromFilename: true
    fromContent: false
    asciiOnly: false
    lowercase: false
  itemsPerPage: 10
customizations:
  sidebar: _sidebar.md
  footer: _footer.md
  style: _style.css
  script: _script.js

